# Site
repository: https://github.com/munirdin87/
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Munirdin Jadikar
title: Data Scientist 
email: jadikar@gmail.com
website: https://github.com/munirdin87/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  munirdin87
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
#- title: itsgoingto.be
 # icon: fas fa-globe
  #url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Hey there! I'm an airman with 5 years of experience in air force information systems. After serving my country, I decided to pursue a career in data science, and I recently earned a master's degree in the field. 
  I'm passionate about working on complex data problems and using my skills to develop machine learning models that solve real-world business problems. 
  Whether it's analyzing large data sets or building predictive models, I love using my expertise to help organizations make data-driven decisions.
  I am most skilled in: <mark>Deep learning</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: https://github.com/munirdin87/bone_lesion_classification
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          about project
        description: | # this will include new lines to allow paragraphs
         about project 
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Elisabeth-tweesteden hospital
        link: www.etz.nl/WeCare/Home
        # link_text: boringcompany.com
        sub_title: Data Scientist
        caption: June 2022 - January 2023

        description: | # this will include new lines to allow paragraphs
          I developed and implemented a classification model with transfer
          learning to accurately classify bone lesions from multiple myeloma.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tilburg University
        caption: 2021 - 2023
        sub_title: MSc data science
        description: | # this will include new lines to allow paragraphs
          about master 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
